import{stageConfig,generatePath}from'./game.js';import{DEFAULT_DATA,loadData,saveData}from'./storage.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const screens=$$('.screen'),board=$('#board'),overlay=$('#overlay');let data=loadData(),run=null,timer=0,sessionStarted=0,audioCtx;
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===`${id}-screen`));if(id==='home')renderHome();if(id==='stats')renderStats();if(id==='settings')renderSettings()}
function renderHome(){$('#home-best').textContent=data.highestStage;$('#continue-label').textContent=`Bestwert: Stage ${data.highestStage}`}
function renderLives(){const el=$('#lives');el.innerHTML=[0,1,2].map(i=>`<span class="heart ${i>=run.lives?'lost':''}">♥</span>`).join('');el.setAttribute('aria-label',`${run.lives} Leben`)}
function renderSettings(){$$('.toggle-row').forEach(b=>b.classList.toggle('on',data.settings[b.dataset.setting]))}
function renderStats(){const accuracy=data.stats.attempts?Math.round(data.stats.correct/data.stats.attempts*100):0;const items=[['HÖCHSTE STAGE',data.highestStage],['RUNS',data.stats.runs],['STAGES GESCHAFFT',data.stats.stagesCleared],['BESTER STREAK',data.stats.bestStreak],['GENAUIGKEIT',`${accuracy}%`],['SPIELZEIT',`${Math.floor(data.stats.totalSeconds/60)} min`]];$('#stats-grid').innerHTML=items.map(([a,b])=>`<div class="stat-card"><span>${a}</span><b>${b}</b></div>`).join('')}
function persist(){saveData(data)}function tone(type){if(!data.settings.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;const map={tap:[520,.06],ok:[680,.09],bad:[150,.18],win:[880,.3]};o.frequency.setValueAtTime(map[type][0],now);if(type==='win')o.frequency.exponentialRampToValueAtTime(1320,now+.25);g.gain.setValueAtTime(.075,now);g.gain.exponentialRampToValueAtTime(.001,now+map[type][1]);o.connect(g).connect(audioCtx.destination);o.start();o.stop(now+map[type][1])}catch{}}
function buzz(pattern){if(data.settings.haptics&&navigator.vibrate)navigator.vibrate(pattern)}
function startRun(){data.stats.runs++;persist();run={stage:1,lives:3,streak:0,seed:(Date.now()^Math.random()*2**31)>>>0,path:null,input:0,phase:'idle',mistakes:0};sessionStarted=Date.now();show('game');startStage(true)}
function startStage(newPath){clearTimeout(timer);const cfg=stageConfig(run.stage);if(newPath||!run.path){run.seed=(run.seed+0x9e3779b9)>>>0;run.path=generatePath(cfg,run.seed)}run.cfg=cfg;run.input=0;run.phase='show';renderBoard();renderLives();$('#stage-value').textContent=run.stage;$('#streak-value').textContent=run.streak;$('#phase-title').textContent='MERKEN';$('#phase-copy').textContent=cfg.recovery?'Kurze Erholung – du schaffst das':'Präge dir die Reihenfolge ein';$('#phase-pill').style.color='var(--purple)';updateProgress();timer=setTimeout(beginInput,cfg.reveal)}
function renderBoard(){const{cols,rows}=run.cfg;board.style.setProperty('--cols',cols);board.style.setProperty('--rows',rows);const positions=new Map(run.path.map((p,i)=>[`${p.x},${p.y}`,i]));board.innerHTML='';for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const b=document.createElement('button');b.className='cell';b.setAttribute('role','gridcell');b.dataset.x=x;b.dataset.y=y;b.disabled=run.phase!=='input';const index=positions.get(`${x},${y}`);if(run.phase==='show'&&index!==undefined){b.classList.add('path');if(index===0)b.classList.add('start');b.dataset.order=index+1;b.style.setProperty('--order',index)}board.append(b)}}
function beginInput(){run.phase='input';renderBoard();$('#phase-title').textContent='JETZT DU';$('#phase-copy').textContent='Tippe den Pfad in der richtigen Reihenfolge';$('#phase-pill').style.color='var(--mint)';if(!data.tutorialDone)cellAt(run.path[0]).classList.add('hint')}
function cellAt(p){return board.querySelector(`[data-x="${p.x}"][data-y="${p.y}"]`)}
function updateProgress(){$('#progress-label').textContent=`PFAD ${run.input} / ${run.path.length}`;$('#progress-bar').style.width=`${run.input/run.path.length*100}%`}
function tapCell(cell){if(run.phase!=='input')return;const want=run.path[run.input],hit=+cell.dataset.x===want.x&&+cell.dataset.y===want.y;data.stats.attempts++;if(hit){data.stats.correct++;cell.classList.remove('hint');cell.classList.add('correct','pop');run.input++;tone('ok');buzz(12);updateProgress();if(run.input===run.path.length)stageWon()}else{cell.classList.add('wrong');run.phase='locked';run.lives--;run.streak=0;run.mistakes++;renderLives();tone('bad');buzz([35,35,55]);$('#game-screen').classList.add('shake');setTimeout(()=>$('#game-screen').classList.remove('shake'),400);timer=setTimeout(()=>handleMiss(),500)}persist()}
function handleMiss(){if(run.lives<=0)return gameOver();dialog({icon:'♡',kicker:'NICHT AUFGEBEN',title:'Fast geschafft!',copy:'Du siehst genau denselben Pfad noch einmal. Beim nächsten Versuch sitzt er.',score:'Keine neuen Überraschungen',primary:'PFAD NOCHMAL',action:()=>startStage(false),secondary:'RUN BEENDEN',secondaryAction:gameOver})}
function stageWon(){run.phase='locked';run.streak++;data.stats.stagesCleared++;data.stats.bestStreak=Math.max(data.stats.bestStreak,run.streak);data.highestStage=Math.max(data.highestStage,run.stage+1);data.highScore=Math.max(data.highScore,run.stage*100+run.streak*25);data.tutorialDone=true;persist();tone('win');buzz([20,30,20]);particles();timer=setTimeout(()=>dialog({icon:'✦',kicker:run.mistakes?'STAGE GESCHAFFT':'PERFECT',title:run.mistakes?'Sehr gut!':'Makellos!',copy:run.mistakes?'Du hast den Pfad gemeistert.':'Ohne einen Fehler – dein Streak wächst.',score:`STREAK ${run.streak} · +${100+run.streak*25} PUNKTE`,primary:'WEITER',action:()=>{run.stage++;run.path=null;run.mistakes=0;startStage(true)}}),450)}
function gameOver(){clearTimeout(timer);if(sessionStarted){data.stats.totalSeconds+=Math.round((Date.now()-sessionStarted)/1000);sessionStarted=0;persist()}dialog({icon:'◇',kicker:'RUN BEENDET',title:`Stage ${run.stage}`,copy:`Deine Bestleistung ist Stage ${data.highestStage}. Ein neuer Versuch startet sofort.`,score:`${data.stats.correct} richtige Felder insgesamt`,primary:'NOCH EIN RUN',action:startRun,secondary:'HAUPTMENÜ',secondaryAction:()=>show('home')})}
function dialog(o){$('#dialog-icon').textContent=o.icon;$('#dialog-kicker').textContent=o.kicker;$('#dialog-title').textContent=o.title;$('#dialog-copy').textContent=o.copy;$('#dialog-score').textContent=o.score||'';const a=$('#dialog-primary'),b=$('#dialog-secondary');a.textContent=o.primary;a.onclick=()=>{overlay.classList.remove('show');overlay.setAttribute('aria-hidden','true');o.action?.()};b.hidden=!o.secondary;b.textContent=o.secondary||'';b.onclick=()=>{overlay.classList.remove('show');overlay.setAttribute('aria-hidden','true');o.secondaryAction?.()};overlay.classList.add('show');overlay.setAttribute('aria-hidden','false');a.focus()}
function particles(){if(!data.settings.motion)return;const box=$('#particles');for(let i=0;i<24;i++){const p=document.createElement('i');p.className='particle';p.style.left=`${45+Math.random()*10}%`;p.style.top='50%';p.style.background=i%2?'var(--mint)':'var(--purple)';p.style.setProperty('--dx',`${(Math.random()-.5)*320}px`);p.style.setProperty('--dy',`${(Math.random()-.75)*380}px`);box.append(p);setTimeout(()=>p.remove(),900)}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
board.addEventListener('click',e=>{const c=e.target.closest('.cell');if(c)tapCell(c)});$('#play-button').onclick=startRun;$('#pause-button').onclick=()=>{const wasShowing=run.phase==='show';if(wasShowing){clearTimeout(timer);run.phase='paused'}dialog({icon:'Ⅱ',kicker:'KURZE PAUSE',title:'Bereit?',copy:'Der aktuelle Pfad bleibt erhalten.',primary:'WEITERSPIELEN',action:()=>{if(wasShowing)startStage(false)},secondary:'HAUPTMENÜ',secondaryAction:()=>{clearTimeout(timer);show('home')}})};$('#sound-quick').onclick=()=>{data.settings.sound=!data.settings.sound;persist();toast(data.settings.sound?'Sound an':'Sound aus')};$$('[data-open]').forEach(b=>b.onclick=()=>show(b.dataset.open));$$('[data-back]').forEach(b=>b.onclick=()=>show('home'));$$('.toggle-row').forEach(b=>b.onclick=()=>{const k=b.dataset.setting;data.settings[k]=!data.settings[k];persist();renderSettings();tone('tap')});$('#reset-progress').onclick=()=>dialog({icon:'↺',kicker:'SICHER?',title:'Alles zurücksetzen?',copy:'Bestleistungen, Statistik und Einstellungen werden gelöscht.',primary:'ZURÜCKSETZEN',action:()=>{data=JSON.parse(JSON.stringify(DEFAULT_DATA));persist();renderSettings();toast('Fortschritt gelöscht')},secondary:'ABBRECHEN',secondaryAction:()=>{}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&run&&run.phase==='show'){clearTimeout(timer);run.phase='paused';dialog({icon:'◌',kicker:'PAUSIERT',title:'Pfad geschützt',copy:'Wir zeigen dir den Pfad noch einmal, damit es fair bleibt.',primary:'WEITER',action:()=>startStage(false)})}});addEventListener('beforeunload',()=>{if(sessionStarted){data.stats.totalSeconds+=Math.round((Date.now()-sessionStarted)/1000);persist()}});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));renderHome();
